# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2021-06-10 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='feedback',
        ),
    ]
